# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34a92889278c406baee4c8f62f8ae5741f0e72afd49180cdb68164d10fc8dbf19f1cb4c07a3fa14436c25191e9ce3c3f4fa0924ffb987ed8f4656ca2f0580959

test:
  secret_key_base: 07fa1601a7bede7eedf3d599cbc0797c585e5483abb4d1be6561956717c05eac9f7b4a7761e2f0fab7cd07d5edd22ef1a48d08e639024b1b20cbedc8d1b48d9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
